# Base URL's
OMSUI_URL=http://10.249.36.21:9097
ORCH_URL=http://10.249.36.21:9093
AUTH_URL=http://10.249.36.21:9091

# Product Version
# Possible Values: 6.0,6.1,5.0,5.1
version=6.0
# Browser details
browser=chrome

# Archival Database details
datasourceDriverClassName=org.postgresql.Driver
archivalDsUrl=jdbc:postgresql://10.249.36.17:5432/archivaldbll610_mud?currentSchema=archivalschemall610_mud
archivalDsUsername=archivaluserll610_mud
archivalDsPassword=archivaluserll610_mud